name: GitGoogleContainer
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACCESS_NAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Docker pull and push
        run: |
          calico_version=v3.23.3
          podname=calico
          for i in cni node kube-controllers pod2daemon-flexvol
          do
            docker pull $podname/$i:$calico_version
            docker tag  $podname/$i:$calico_version registry.cn-shanghai.aliyuncs.com/asvex/$i:$calico_version
            docker push registry.cn-shanghai.aliyuncs.com/asvex/$i:$calico_version
          done
          docker pull k8s.gcr.io/autoscaling/vpa-admission-controller:0.10.0
          docker tag k8s.gcr.io/autoscaling/vpa-admission-controller:0.10.0 registry.cn-shanghai.aliyuncs.com/asvex/vpa-admission-controller:0.10.0
          docker push registry.cn-shanghai.aliyuncs.com/asvex/vpa-admission-controller:0.10.0
          docker pull centos:7.9.2009
          docker tag centos:7.9.2009 registry.cn-shanghai.aliyuncs.com/asvex/centos:7.9.2009
          docker push registry.cn-shanghai.aliyuncs.com/asvex/centos:7.9.2009
