name: GitGoogleContainer
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACCESS_NAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Docker pull and push
        run: |
          # calico_version=v3.32.1
          # docker pull quay.io/calico/calico:master
          # docker tag quay.io/calico/calico:master registry.cn-shanghai.aliyuncs.com/asvex/calico:master
          # docker push registry.cn-shanghai.aliyuncs.com/asvex/calico:master
          # podname=calico
          # for i in cni node kube-controllers pod2daemon-flexvol
          # do
          #   docker pull $podname/$i:$calico_version
          #   docker tag  $podname/$i:$calico_version registry.cn-shanghai.aliyuncs.com/asvex/$i:$calico_version
          #   docker push registry.cn-shanghai.aliyuncs.com/asvex/$i:$calico_version
          # done
          # docker pull k8s.gcr.io/autoscaling/vpa-admission-controller:0.10.0
          # docker tag k8s.gcr.io/autoscaling/vpa-admission-controller:0.10.0 registry.cn-shanghai.aliyuncs.com/asvex/vpa-admission-controller:0.10.0
          # docker push registry.cn-shanghai.aliyuncs.com/asvex/vpa-admission-controller:0.10.0
          # docker pull registry.k8s.io/pause:3.10.1
          # docker tag registry.k8s.io/pause:3.10.1 registry.cn-shanghai.aliyuncs.com/asvex/pause:3.10.1
          # docker push registry.cn-shanghai.aliyuncs.com/asvex/pause:3.10.1
          
          docker pull ghcr.io/flannel-io/flannel:v0.28.5
          docker tag ghcr.io/flannel-io/flannel:v0.28.5 registry.cn-shanghai.aliyuncs.com/asvex/flannel:v0.28.5
          docker push registry.cn-shanghai.aliyuncs.com/asvex/flannel:v0.28.5
          docker pull ghcr.io/flannel-io/flannel-cni-plugin:v1.9.1-flannel1
          docker tag ghcr.io/flannel-io/flannel-cni-plugin:v1.9.1-flannel1 registry.cn-shanghai.aliyuncs.com/asvex/flannel-cni-plugin:v1.9.1-flannel1
          docker push registry.cn-shanghai.aliyuncs.com/asvex/flannel-cni-plugin:v1.9.1-flannel1
